### ISSUE TITLE
Soundy is too good

### ISSUE THREAD

**Issue by TheCoolerMS3** [ivanghi1995/Soundy#1]
Soundy is too good fix it pls

**Comment by Ivaniku** [comment]
This can't be fixed since Soundy is perfect

**Comment by laniku** [comment]
> This can't be fixed since Soundy is perfect

But that is the issue, it being too good/perfect.

**Comment by Ivaniku** [comment]
> > This can't be fixed since Soundy is perfect
> 
> But that is the issue, it being too good/perfect.

But it can't be fixed
